[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.?venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
plugins = ['sqlalchemy.ext.mypy.plugin']
ignore_missing_imports = true
