---
applications:
- name: ((APP_NAME))
  memory: 256M
  instances: 1
  command: ./scripts/run-worker
  no-route: true
  health-check-type: process
  services:
  - ((CDN_DB_NAME))
  - ((DOMAIN_DB_NAME))
  - ((REDIS_NAME))
  buildpacks:
  - python_buildpack
  stack: cflinuxfs4
  env:
    ENV: ((ENV))
