---
applications:
- name: ((APP_NAME))
  memory: 256M
  instances: 3
  command: sleep 3600
  services:
  - ((CDN_DB_NAME))
  - ((DOMAIN_DB_NAME))
  buildpacks:
  - python_buildpack
  stack: cflinuxfs4
  env:
    ENV: ((ENV))
    CDN_DATABASE_ENCRYPTION_KEY: ((CDN_DATABASE_ENCRYPTION_KEY))
    DOMAIN_DATABASE_ENCRYPTION_KEY: ((DOMAIN_DATABASE_ENCRYPTION_KEY))
