#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -xeuo pipefail

./docker/start-servers.sh
alembic -c migrations/alembic.ini upgrade head


if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  SQLALCHEMY_WARN_20=1 ptw . "$@"
else
  SQLALCHEMY_WARN_20=1 python -m pytest "$@"
fi

./docker/stop-servers.sh
