"""add more certificate metadata

Revision ID: 23319464f990
Revises: 46f261240bcb
Create Date: 2021-09-15 22:27:50.076291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23319464f990"
down_revision = "46f261240bcb"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("certificates", sa.Column("fullchain_pem", sa.Text(), nullable=True))
    op.add_column("certificates", sa.Column("leaf_pem", sa.Text(), nullable=True))
    op.add_column(
        "certificates", sa.Column("iam_server_certificate_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "certificates",
        sa.Column("iam_server_certificate_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "certificates",
        sa.Column("iam_server_certificate_arn", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("certificates", "iam_server_certificate_arn")
    op.drop_column("certificates", "iam_server_certificate_name")
    op.drop_column("certificates", "iam_server_certificate_id")
    op.drop_column("certificates", "leaf_pem")
    op.drop_column("certificates", "fullchain_pem")
    # ### end Alembic commands ###


def upgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("certificates", sa.Column("fullchain_pem", sa.Text(), nullable=True))
    op.add_column("certificates", sa.Column("leaf_pem", sa.Text(), nullable=True))
    op.add_column(
        "certificates", sa.Column("iam_server_certificate_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "certificates",
        sa.Column("iam_server_certificate_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "certificates",
        sa.Column("iam_server_certificate_arn", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("certificates", "iam_server_certificate_arn")
    op.drop_column("certificates", "iam_server_certificate_name")
    op.drop_column("certificates", "iam_server_certificate_id")
    op.drop_column("certificates", "leaf_pem")
    op.drop_column("certificates", "fullchain_pem")
    # ### end Alembic commands ###
