"""add challenge and order tracking

Revision ID: dea7e9aea52b
Revises: 0d14cc3a1cf1
Create Date: 2021-09-13 23:50:34.643782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dea7e9aea52b"
down_revision = "0d14cc3a1cf1"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("certificate_id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("validation_domain", sa.String(), nullable=False),
        sa.Column("validation_contents", sa.Text(), nullable=False),
        sa.Column("body_json", sa.Text(), nullable=True),
        sa.Column("answered", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_challenges_certificate_id_certificates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.add_column("certificates", sa.Column("order_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("certificates", "order_json")
    op.drop_table("challenges")
    # ### end Alembic commands ###


def upgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("certificate_id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("validation_domain", sa.String(), nullable=False),
        sa.Column("validation_contents", sa.Text(), nullable=False),
        sa.Column("body_json", sa.Text(), nullable=True),
        sa.Column("answered", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_challenges_certificate_id_certificates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.add_column("certificates", sa.Column("order_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("certificates", "order_json")
    op.drop_table("challenges")
    # ### end Alembic commands ###
