"""add operation models

Revision ID: fed9ab0d1672
Revises: cf25238724b3
Create Date: 2021-08-25 16:25:56.141264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fed9ab0d1672"
down_revision = "cf25238724b3"
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), server_default="in progress", nullable=False),
        sa.Column("action", sa.Text(), server_default="renew", nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], name=op.f("fk_operations_route_id_routes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
    )
    # ### end Alembic commands ###


def downgrade_cdn():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operations")
    # ### end Alembic commands ###


def upgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_guid", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="in progress", nullable=False),
        sa.Column("action", sa.Text(), server_default="renew", nullable=False),
        sa.ForeignKeyConstraint(
            ["route_guid"],
            ["routes.guid"],
            name=op.f("fk_operations_route_guid_routes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
    )
    # ### end Alembic commands ###


def downgrade_domain():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operations")
    # ### end Alembic commands ###
