---
upgrade-schema-vars: &upgrade-schema-vars
  APP_NAME: ((name))-db-upgrade
  CDN_DB_NAME: ((cdn_db_name))
  DOMAIN_DB_NAME: ((domain_db_name))

cf-manifest-vars: &cf-manifest-vars
  vars:
    APP_NAME: ((name))
    CDN_DB_NAME: ((cdn_db_name))
    DOMAIN_DB_NAME: ((domain_db_name))
    REDIS_NAME: ((redis_name))

create-redis-service-params: &create-redis-service-params
  APP_NAME: ((name))
  SVC_SERVICE: ((redis_service))
  SVC_PLAN: ((redis_plan))
  SVC_NAME: ((redis_name))

cf-creds-dev: &cf-creds-dev
  CF_API_URL: ((dev-cf-api-endpoint))
  CF_USERNAME: ((dev-cf-username))
  CF_PASSWORD: ((dev-cf-password))
  CF_ORGANIZATION: ((cf-organization))
  CF_SPACE: ((cf-space))

cf-creds-staging: &cf-creds-staging
  CF_API_URL: ((staging-cf-api-endpoint))
  CF_USERNAME: ((staging-cf-username))
  CF_PASSWORD: ((staging-cf-password))
  CF_ORGANIZATION: ((cf-organization))
  CF_SPACE: ((cf-space))

cf-creds-production: &cf-creds-production
  CF_API_URL: ((production-cf-api-endpoint))
  CF_USERNAME: ((production-cf-username))
  CF_PASSWORD: ((production-cf-password))
  CF_ORGANIZATION: ((cf-organization))
  CF_SPACE: ((cf-space))
jobs:

- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [reconfigure]

  - put: dev-docker-image
    # We push this docker image _only_ so that we can use it in the next task
    # below.  :shrug: concourse.
    params:
      build: src
      dockerfile: src/docker/Dockerfile.dev
      tag_as_latest: true
      cache: true

  - task: test
    # Run mypy using the image pushed above.
    image: dev-docker-image
    config:
      platform: linux
      params:
        TMPDIR: /tmp
      run:
        path: /app/docker/mypy

  - task: test
    # Run the tests using the image pushed above.
    image: dev-docker-image
    config:
      platform: linux
      params:
        TMPDIR: /tmp
      run:
        path: /app/docker/tests

- name: dev
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [test]
    - get: pipeline-tasks
  - task: create-redis
    file: pipeline-tasks/ensure-misbehaved-service.yml
    params:
      <<: *cf-creds-dev
      <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-dev
      APPLICATIONS: "((name))"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-dev
      <<: *upgrade-schema-vars
      CDN_DATABASE_ENCRYPTION_KEY: ((dev-cdn-database-encryption-key))
      DOMAIN_DATABASE_ENCRYPTION_KEY: ((dev-domain-database-encryption-key))
  - put: cf-dev
    params:
      path: src
      manifest: src/manifests/renewer.yml
      show_app_log: true
      <<: *cf-manifest-vars
      environment_variables:
        ENV: development
        AWS_POLL_WAIT_TIME_IN_SECONDS: ((aws-poll-time-in-seconds))
        AWS_POLL_MAX_ATTEMPTS: ((aws-poll-max-attempts))
        IAM_PROPAGATION_TIME: ((iam-propagation-time))
        AWS_COMMERCIAL_REGION: ((dev-aws-commercial-region))
        AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((dev-aws-commercial-secret-access-key))
        AWS_COMMERCIAL_ACCESS_KEY_ID: ((dev-aws-commercial-access-key-id))
        COMMERCIAL_BUCKET: ((dev-commercial-bucket))
        COMMERCIAL_IAM_PREFIX: ((dev-commercial-iam-prefix))
        AWS_GOVCLOUD_REGION: ((dev-aws-govcloud-region))
        AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((dev-aws-govcloud-secret-access-key))
        AWS_GOVCLOUD_ACCESS_KEY_ID: ((dev-aws-govcloud-access-key-id))
        GOVCLOUD_BUCKET: ((dev-govcloud-bucket))
        GOVCLOUD_IAM_PREFIX: ((dev-govcloud-iam-prefix))
        LETS_ENCRYPT_REGISTRATION_EMAIL: ((lets_encrypt_registration_email))
        CDN_DATABASE_ENCRYPTION_KEY: ((dev-cdn-database-encryption-key))
        DOMAIN_DATABASE_ENCRYPTION_KEY: ((dev-domain-database-encryption-key))
        SMTP_PASS: ((dev-smtp-pass))
        SMTP_HOST: ((dev-smtp-host))
        SMTP_USER: ((dev-smtp-user))
        SMTP_FROM: ((dev-smtp-from))
        SMTP_PORT: ((dev-smtp-port))
        SMTP_TO: ((dev-smtp-to))
        SMTP_CERT: ((dev-smtp-cert)
        SMTP_TLS: ((dev-smtp-tls))
        LOG_LEVEL: ((dev-log-level))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy legacy-domain-certificate-renewer on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed legacy-domain-certificate-renewer on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))


- name: staging
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [dev]
    - get: pipeline-tasks
  - task: create-redis
    file: pipeline-tasks/ensure-misbehaved-service.yml
    params:
      <<: *cf-creds-staging
      <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-staging
      APPLICATIONS: "((name))"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-staging
      <<: *upgrade-schema-vars
      CDN_DATABASE_ENCRYPTION_KEY: ((staging-cdn-database-encryption-key))
      DOMAIN_DATABASE_ENCRYPTION_KEY: ((staging-domain-database-encryption-key))
  - put: cf-staging
    params:
      path: src
      manifest: src/manifests/renewer.yml
      show_app_log: true
      <<: *cf-manifest-vars
      environment_variables:
        ENV: staging
        AWS_POLL_WAIT_TIME_IN_SECONDS: ((aws-poll-time-in-seconds))
        AWS_POLL_MAX_ATTEMPTS: ((aws-poll-max-attempts))
        IAM_PROPAGATION_TIME: ((iam-propagation-time))
        AWS_COMMERCIAL_REGION: ((staging-aws-commercial-region))
        AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((staging-aws-commercial-secret-access-key))
        AWS_COMMERCIAL_ACCESS_KEY_ID: ((staging-aws-commercial-access-key-id))
        COMMERCIAL_BUCKET: ((staging-commercial-bucket))
        COMMERCIAL_IAM_PREFIX: ((staging-commercial-iam-prefix))
        AWS_GOVCLOUD_REGION: ((staging-aws-govcloud-region))
        AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((staging-aws-govcloud-secret-access-key))
        AWS_GOVCLOUD_ACCESS_KEY_ID: ((staging-aws-govcloud-access-key-id))
        GOVCLOUD_BUCKET: ((staging-govcloud-bucket))
        GOVCLOUD_IAM_PREFIX: ((staging-govcloud-iam-prefix))
        LETS_ENCRYPT_REGISTRATION_EMAIL: ((lets_encrypt_registration_email))
        CDN_DATABASE_ENCRYPTION_KEY: ((staging-cdn-database-encryption-key))
        DOMAIN_DATABASE_ENCRYPTION_KEY: ((staging-domain-database-encryption-key))
        RUN_RENEWALS: ((staging-run-renewals))
        RUN_BACKPORTS: ((staging-run-backports))
        SMTP_PASS: ((staging-smtp-pass))
        SMTP_HOST: ((staging-smtp-host))
        SMTP_USER: ((staging-smtp-user))
        SMTP_FROM: ((staging-smtp-from))
        SMTP_PORT: ((staging-smtp-port))
        SMTP_TO: ((staging-smtp-to))
        SMTP_TLS: ((staging-smtp-tls))
        LOG_LEVEL: ((staging-log-level))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy legacy-domain-certificate-renewer on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed legacy-domain-certificate-renewer on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))


- name: production
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [staging]
    - get: pipeline-tasks
  - task: create-redis
    file: pipeline-tasks/ensure-misbehaved-service.yml
    params:
      <<: *cf-creds-production
      <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-production
      APPLICATIONS: "((name))"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-production
      <<: *upgrade-schema-vars
      CDN_DATABASE_ENCRYPTION_KEY: ((production-cdn-database-encryption-key))
      DOMAIN_DATABASE_ENCRYPTION_KEY: ((production-domain-database-encryption-key))
  - put: cf-production
    params:
      path: src
      manifest: src/manifests/renewer.yml
      show_app_log: true
      <<: *cf-manifest-vars
      environment_variables:
        ENV: production
        AWS_POLL_WAIT_TIME_IN_SECONDS: ((aws-poll-time-in-seconds))
        AWS_POLL_MAX_ATTEMPTS: ((aws-poll-max-attempts))
        IAM_PROPAGATION_TIME: ((iam-propagation-time))
        AWS_COMMERCIAL_REGION: ((production-aws-commercial-region))
        AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((production-aws-commercial-secret-access-key))
        AWS_COMMERCIAL_ACCESS_KEY_ID: ((production-aws-commercial-access-key-id))
        COMMERCIAL_BUCKET: ((production-commercial-bucket))
        COMMERCIAL_IAM_PREFIX: ((production-commercial-iam-prefix))
        AWS_GOVCLOUD_REGION: ((production-aws-govcloud-region))
        AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((production-aws-govcloud-secret-access-key))
        AWS_GOVCLOUD_ACCESS_KEY_ID: ((production-aws-govcloud-access-key-id))
        GOVCLOUD_BUCKET: ((production-govcloud-bucket))
        GOVCLOUD_IAM_PREFIX: ((production-govcloud-iam-prefix))
        LETS_ENCRYPT_REGISTRATION_EMAIL: ((lets_encrypt_registration_email))
        CDN_DATABASE_ENCRYPTION_KEY: ((production-cdn-database-encryption-key))
        DOMAIN_DATABASE_ENCRYPTION_KEY: ((production-domain-database-encryption-key))
        RUN_RENEWALS: ((production-run-renewals))
        RUN_BACKPORTS: ((production-run-backports))
        SMTP_PASS: ((production-smtp-pass))
        SMTP_HOST: ((production-smtp-host))
        SMTP_USER: ((production-smtp-user))
        SMTP_FROM: ((production-smtp-from))
        SMTP_PORT: ((production-smtp-port))
        SMTP_TO: ((production-smtp-to))
        SMTP_TLS: ((production-smtp-tls))
        LOG_LEVEL: ((production-log-level))

  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy legacy-domain-certificate-renewer on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed legacy-domain-certificate-renewer on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

############################
#  RESOURCES

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: dev-docker-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image-dev))

- name: cf-dev
  type: cf
  icon: cloud-upload
  source:
    api: ((dev-cf-api-endpoint))
    username: ((dev-cf-username))
    password: ((dev-cf-password))
    organization: ((cf-organization))
    space: ((cf-space))

- name: cf-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((staging-cf-api-endpoint))
    username: ((staging-cf-username))
    password: ((staging-cf-password))
    organization: ((cf-organization))
    space: ((cf-space))

- name: cf-production
  type: cf
  icon: cloud-upload
  source:
    api: ((production-cf-api-endpoint))
    username: ((production-cf-username))
    password: ((production-cf-password))
    organization: ((cf-organization))
    space: ((cf-space))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: pipeline-tasks
  type: git
  icon: github-circle
  source:
    uri: ((pipeline-tasks-git-url))
    branch: ((pipeline-tasks-git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

############################
#  RESOURCE TYPES

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
